image: php:7.2-fpm

pipelines:
    custom:
      initialize_server:
        - step:
            name: Initialize server
            script:
              - ls -la
      create_staging_database:
        - step:
            name: Create staging database
            script:
              - ls -la
      create development_database:
        - step:
            name: Create development database
            script:
              - ls -la
    tags:
      v*:
        - step:
            image: composer
            name: Build
            caches:
              - composer
            script:
              - ls -la
        - step:
            image:
              name: registry.mountain-it.nl/mountain-it/base-php
              username: registry
              password: $REGISTRY_PASSWD
            trigger: manual
            name: Deploy to staging
            deployment: staging
            script:
              - ls -la
        - step:
            image:
              name: registry.mountain-it.nl/mountain-it/base-php
              username: registry
              password: $REGISTRY_PASSWD
            trigger: manual
            name: Deploy to production
            deployment: production
            script:
              - ls -la


