image: php:7.2-fpm

pipelines:

  tags:
    v*:
      - step:
          name: Deployment
          script:
            - apt-get update && apt-get install -qy git curl libmcrypt-dev mysql-client
            - yes | pecl install mcrypt-1.0.1
            - docker-php-ext-install pdo_mysql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - rsync -a . root@206.189.110.154:/var/www/configurator
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - ./vendor/bin/phpunit
            - curl -vk http://localhost:8000
          services:
            - mysql
          trigger: manual

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'configurator'
        MYSQL_RANDOM_ROOT_PASSWORD: 'no'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ''
